spring.application.name=dawFinalProyect
spring.banner.location=/banner.txt
# server.servlet.context-path=/daw
server.port=${PORT:8080}

# Configuracion de Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/web/
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

# Database connection - POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configuracion de Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuracion de HikariCP
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED 
spring.datasource.hikari.pool-name=daw135HikariPool


# Auth0 Configuration
spring.security.oauth2.client.registration.auth0.client-id=${AUTH0_CLIENT_ID}
spring.security.oauth2.client.registration.auth0.client-secret=${AUTH0_CLIENT_SECRET}
spring.security.oauth2.client.registration.auth0.scope=${AUTH0_SCOPE}
spring.security.oauth2.client.registration.auth0.redirect-uri=${AUTH0_REDIRECT_URI}
spring.security.oauth2.client.registration.auth0.authorization-grant-type=${AUTH0_AUTHORIZATION_GRANT_TYPE}
spring.security.oauth2.client.provider.auth0.issuer-uri=${AUTH0_ISSUER_URI}